import { Html, Head, Body } from '@react-email/components';

type Props = {
  title: string;
  children: React.ReactNode;
  timestamp?: string;
};

export function EmailLayout({ title, children, timestamp }: Props) {
  return (
    <Html>
      <Head />
      <Body style={{ margin: 0, padding: 0, backgroundColor: '#f5f5f3', fontFamily: 'Inter, Arial, sans-serif' }}>
        <table cellPadding={0} cellSpacing={0} width="100%" style={{ borderCollapse: 'collapse', backgroundColor: '#f5f5f3' }}>
          <tbody>
            <tr>
              <td align="center" style={{ padding: '40px 16px' }}>
                <table cellPadding={0} cellSpacing={0} width="600" style={{ borderCollapse: 'collapse', maxWidth: '600px', width: '100%' }}>
                  <tbody>
                    <tr>
                      <td style={{ paddingBottom: '20px', borderBottom: '1px solid #e8e8e6' }}>
                        <p style={{ margin: '0 0 8px 0', fontSize: '11px', fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#999999' }}>
                          Tindy Works
                        </p>
                        <h1 style={{ margin: 0, fontSize: '22px', fontWeight: 700, color: '#111111', letterSpacing: '-0.02em', lineHeight: '1.3' }}>
                          {title}
                        </h1>
                      </td>
                    </tr>
                    <tr>
                      <td style={{ paddingTop: '28px' }}>{children}</td>
                    </tr>
                    <tr>
                      <td align="center" style={{ padding: '32px 0 8px' }}>
                        <p style={{ margin: 0, fontSize: '11px', color: '#bbbbbb', letterSpacing: '0.02em' }}>
                          {'Generated by Tindy Works'}{timestamp ? ` · ${timestamp}` : ''}
                        </p>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </Body>
    </Html>
  );
}
